CREATE DATABASE IF NOT EXISTS db_users;

USE db_users;

CREATE TABLE TB_USERS(
  USE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USE_NAME VARCHAR(255) NOT NULL,
  USE_EMAIL VARCHAR(255) NOT NULL,
  USE_COUNTRY VARCHAR(50) NOT NULL,
  USE_STATE VARCHAR(50) NOT NULL,
  USE_CITY VARCHAR(50) NOT NULL,
  USE_CEP VARCHAR(8) NOT NULL,
  USE_STREET VARCHAR(50) NOT NULL,
  USE_NUMBER VARCHAR(10) NOT NULL,
  USE_COMPLEMENT VARCHAR(50) NOT NULL,
  USE_CPF VARCHAR(11) NOT NULL,
  USE_PIS VARCHAR(11) NOT NULL,
  USE_PASSWORD VARCHAR(255) NOT NULL
);